fill backend db with data

diff --git a/scripts/pre-commit b/scripts/pre-commit
--- a/scripts/pre-commit
+++ b/scripts/pre-commit
@@ -1,5 +1,10 @@
 #!/bin/sh
+
+# ln -s -f ../../scripts/pre-commit .git/hooks/pre-commit
+
 set -e
+
+command -v ktlint >/dev/null 2>&1 || { echo >&2 "ktlint not found.\nAborting."; exit 2; }
 
 FILES=$(git diff --cached --name-only | grep -i -E "\.kts?" || true)
 
@@ -9,6 +14,8 @@ then
 else
     echo "No file for ktlint"
 fi
+
+command -v swiftlint >/dev/null 2>&1 || { echo >&2 "swiftlint not found.\nAborting."; exit 2; }
 
 FILES=$(git diff --cached --name-only | grep -i -E "\.swift" || true)
 
